///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Rx_Git_Integration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Rx_Git_IntegrationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f1c10115-35dd-4ea9-9411-fad7bb74b9bd")]
    public partial class Rx_Git_IntegrationRepository : RepoGenBaseFolder
    {
        static Rx_Git_IntegrationRepository instance = new Rx_Git_IntegrationRepository();
        Rx_Git_IntegrationRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Rx_Git_IntegrationRepository element repository.
        /// </summary>
        [RepositoryFolder("f1c10115-35dd-4ea9-9411-fad7bb74b9bd")]
        public static Rx_Git_IntegrationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Rx_Git_IntegrationRepository() 
            : base("Rx_Git_IntegrationRepository", "/", null, 0, false, "f1c10115-35dd-4ea9-9411-fad7bb74b9bd", ".\\RepositoryImages\\Rx_Git_IntegrationRepositoryf1c10115.rximgres")
        {
            _applicationundertest = new Rx_Git_IntegrationRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f1c10115-35dd-4ea9-9411-fad7bb74b9bd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("7b32829d-ffdc-4cd9-bb32-3016a6f6594d")]
        public virtual Rx_Git_IntegrationRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Rx_Git_IntegrationRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("7b32829d-ffdc-4cd9-bb32-3016a6f6594d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "7b32829d-ffdc-4cd9-bb32-3016a6f6594d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7b32829d-ffdc-4cd9-bb32-3016a6f6594d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7b32829d-ffdc-4cd9-bb32-3016a6f6594d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
